from django.db import models

class DashboardTiles(models.Model):
    class Meta:
        permissions = (
            ('view_own_dashboard_running_tile', 'Can view own dashboard running tile'),
            ('view_all_dashboard_running_tile', 'Can view all dashboard running tile'),
            ('view_manager_dashboard_running_tile', 'Can view manager dashboard running tile'),
            ('view_teamlead_dashboard_running_tile', 'Can view team lead dashboard running tile'),
            ('view_own_dashboard_Pending_tile', 'Can view own dashboard Pending tile'),
            ('view_all_dashboard_Pending_tile', 'Can view all dashboard Pending tile'),
            ('view_manager_dashboard_Pending_tile', 'Can view manager dashboard Pending tile'),
            ('view_teamlead_dashboard_Pending_tile', 'Can view team lead dashboard Pending tile'),
            ('view_own_dashboard_repeat_order_tile', 'Can view own dashboard repeat_order tile'),
            ('view_all_dashboard_repeat_order_tile', 'Can view all dashboard repeat_order tile'),
            ('view_manager_dashboard_repeat_order_tile', 'Can view manager dashboard repeat_order tile'),
            ('view_teamlead_dashboard_repeat_order_tile', 'Can view team lead dashboard repeat_order tile'),
            ('view_own_dashboard_rejected_tile', 'Can view own dashboard rejected tile'),
            ('view_all_dashboard_rejected_tile', 'Can view all dashboard rejected tile'),
            ('view_manager_dashboard_rejected_tile', 'Can view manager dashboard rejected tile'),
            ('view_teamlead_dashboard_rejected_tile', 'Can view team lead dashboard rejected tile'),
            ('view_own_dashboard_in_transit_tile', 'Can view own dashboard in transit tile'),
            ('view_all_dashboard_in_transit_tile', 'Can view all dashboard in transit tile'),
            ('view_manager_dashboard_in_transit_tile', 'Can view manager dashboard in transit tile'),
            ('view_teamlead_dashboard_in_transit_tile', 'Can view team lead dashboard in transit tile'),
            ('view_own_dashboard_accepted_tile', 'Can view own dashboard accepted tile'),
            ('view_all_dashboard_accepted_tile', 'Can view all dashboard accepted tile'),
            ('view_manager_dashboard_accepted_tile', 'Can view manager dashboard accepted tile'),
            ('view_teamlead_dashboard_accepted_tile', 'Can view team lead dashboard accepted tile'),
            ('view_own_dashboard_no_response_tile', 'Can view own dashboard no response tile'),
            ('view_all_dashboard_no_response_tile', 'Can view all dashboard no response tile'),
            ('view_manager_dashboard_no_response_tile', 'Can view manager dashboard no response tile'),
            ('view_teamlead_dashboard_no_response_tile', 'Can view team lead dashboard no response tile'),
            ('view_own_dashboard_total_tile', 'Can view own dashboard total tile'),
            ('view_all_dashboard_total_tile', 'Can view all dashboard total tile'),
            ('view_manager_dashboard_total_tile', 'Can view manager dashboard total tile'),
            ('view_teamlead_dashboard_total_tile', 'Can view team lead dashboard total tile'),
            ('view_own_dashboard_future_tile', 'Can view own dashboard future tile'),
            ('view_all_dashboard_future_tile', 'Can view all dashboard future tile'),
            ('view_manager_dashboard_future_tile', 'Can view manager dashboard future tile'),
            ('view_teamlead_dashboard_future_tile', 'Can view team lead dashboard future tile'),
            ('view_all_dashboard_delivered_tile', 'Can view all dashboard delivered tile'),
            ('view_manager_dashboard_delivered_tile', 'Can view manager dashboard delivered tile'),
            ('view_teamlead_dashboard_delivered_tile', 'Can view team lead dashboard delivered tile'),
            ('view_own_dashboard_schedule_order_chart', 'Can view own dashboard schedule order chart'),
            ('view_all_dashboard_schedule_order_chart', 'Can view all dashboard schedule order chart'),
            ('view_manager_dashboard_schedule_order_chart', 'Can view manager dashboard schedule order chart'),
            ('view_teamlead_dashboard_schedule_order_chart', 'Can view team lead dashboard schedule order chart'),
            ('view_all_dashboard_sales_forecast_chart', 'Can view all dashboard sales forecast chart'),
            ('view_manager_dashboard_sales_forecast_chart', 'Can view manager dashboard sales forecast chart'),
            ('view_teamlead_dashboard_sales_forecast_chart', 'Can view team lead dashboard sales forecast chart'),
            ('view_own_dashboard_top_selling_list', 'Can view own dashboard top selling list'),
            ('view_all_dashboard_top_selling_list', 'Can view all dashboard top selling list'),
            ('view_manager_dashboard_top_selling_list', 'Can view manager dashboard top selling list'),
            ('view_teamlead_dashboard_top_selling_list', 'Can view team lead dashboard top selling list'),
            ('view_own_dashboard_team_order_list', 'Can view own dashboard team order list'),
            ('view_all_dashboard_team_order_list', 'Can view all dashboard team order list'),
            ('view_manager_dashboard_team_order_list', 'Can view manager dashboard team order list'),
            ('view_teamlead_dashboard_team_order_list', 'Can view team lead dashboard team order list'),
            ('view_own_dashboard_in_transit_rto', 'Can view own dashboard in transit rto'),
            ('view_all_dashboard_in_transit_rto', 'Can view all dashboard in transit rto'),
            ('view_manager_dashboard_in_transit_rto', 'Can view manager dashboard in transit rto'),
            ('view_teamlead_dashboard_in_transit_rto', 'Can view team lead dashboard in transit rto'),
            ('view_own_dashboard_rto', 'Can view own dashboard rto'),
            ('view_all_dashboard_rto', 'Can view all dashboard rto'),
            ('view_manager_dashboard_rto', 'Can view manager dashboard rto'),
            ('view_teamlead_dashboard_rto', 'Can view team lead dashboard rto'),
            ('view_own_dashboard_non_serviceable_tile', 'Can view own dashboard non serviceable tile'),
            ('view_all_dashboard_non_serviceable_tile', 'Can view all dashboard non serviceable tile'),
            ('view_manager_dashboard_non_serviceable_tile', 'Can view manager dashboard non serviceable tile'),
            ('view_teamlead_dashboard_non_serviceable_tile', 'Can view team lead dashboard non serviceable tile'),
            ('view_own_dashboard_reattempt_tile', 'Can view own dashboard reattempt tile'),
            ('view_all_dashboard_reattempt_tile', 'Can view all dashboard reattempt tile'),
            ('view_manager_dashboard_reattempt_tile', 'Can view manager dashboard reattempt tile'),
            ('view_teamlead_dashboard_reattempt_tile', 'Can view team lead dashboard reattempt tile'),
            ('view_own_dashboard_ofd_tile', 'Can view own dashboard ofd tile'),
            ('view_all_dashboard_ofd_tile', 'Can view all dashboard ofd tile'),
            ('view_manager_dashboard_ofd_tile', 'Can view manager dashboard ofd tile'),
            ('view_teamlead_dashboard_ofd_tile', 'Can view team lead dashboard ofd tile'),
            ('view_own_dashboard_lost_tile', 'Can view own dashboard lost tile'),
            ('view_all_dashboard_lost_tile', 'Can view all dashboard lost tile'),
            ('view_manager_dashboard_lost_tile', 'Can view manager dashboard lost tile'),
            ('view_teamlead_dashboard_lost_tile', 'Can view team lead dashboard lost tile'),
            ('view_own_dashboard_ndr_tile', 'Can view own dashboard ndr tile'),
            ('view_all_dashboard_ndr_tile', 'Can view all dashboard ndr tile'),
            ('view_manager_dashboard_ndr_tile', 'Can view manager dashboard ndr tile'),
            ('view_teamlead_dashboard_ndr_tile', 'Can view team lead dashboard ndr tile'),
        )
        db_table ='dashboard_table'
    name=models.CharField(max_length=255,blank=True,null=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    def __str__(self):
        return f'{self.name}'