# Generated by Django 5.0.6 on 2024-09-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentmodel',
            name='credential_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentmodel',
            name='credential_password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentmodel',
            name='credential_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentmodel',
            name='credential_username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
