# Generated by Django 5.0.6 on 2024-09-12 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menumodel',
            old_name='ulr',
            new_name='url',
        ),
        migrations.CreateModel(
            name='SubMenuModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('url', models.TextField()),
                ('icon', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin_assets.menumodel')),
            ],
            options={
                'db_table': 'submenu_table',
            },
        ),
    ]
