# Generated by Django 5.0.6 on 2024-12-02 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_qctable'),
        ('superadmin_assets', '0004_bennermodel_pixelcodemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheamSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dark_logo', models.ImageField(upload_to='theam_setting_images/')),
                ('light_logo', models.ImageField(upload_to='theam_setting_images/')),
                ('favicon_logo', models.ImageField(upload_to='theam_setting_images/')),
                ('invoice_logo', models.ImageField(upload_to='theam_setting_images/')),
                ('signature', models.ImageField(upload_to='theam_setting_images/')),
                ('primary_color_code', models.CharField(max_length=255)),
                ('page_theam', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='light', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theam_branch', to='accounts.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theam_company', to='accounts.company')),
            ],
            options={
                'db_table': 'theam_setting_table',
            },
        ),
    ]
