# Generated by Django 5.0.6 on 2024-07-30 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='massage_type',
            field=models.CharField(choices=[('media', 'Media'), ('text', 'Text')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
