# Generated by Django 5.0.6 on 2024-07-30 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_massage_type_chat_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chat',
            table='chat_detail_table',
        ),
    ]
