# Generated by Django 5.0.6 on 2024-07-30 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_chatsession_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='text',
        ),
    ]
