# Generated by Django 5.0.6 on 2024-08-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_chat_chat_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_status',
            field=models.IntegerField(choices=[(0, 'Unread'), (1, 'Read')], default=0),
        ),
    ]
