# Generated by Django 5.0.6 on 2024-08-06 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_chat_chat_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=50)),
                ('group_status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'group_chat_table',
            },
        ),
        migrations.CreateModel(
            name='GroupDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Group_member_status', models.IntegerField(choices=[(0, 'Admin'), (1, 'User')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_id', to=settings.AUTH_USER_MODEL)),
                ('Group_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_member_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_delails_table',
            },
        ),
    ]
