# Generated by Django 5.0.6 on 2024-08-06 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_group_groupdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdetails',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_id', to='chat.group'),
        ),
    ]
