# Generated by Django 5.0.6 on 2024-08-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_groupdetails_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='name',
            field=models.CharField(default='creworder', max_length=50, unique=True),
        ),
    ]
