# Generated by Django 5.0.6 on 2024-08-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'Read'), (0, 'Unread')], default=0),
        ),
    ]
