# Generated by Django 5.0.6 on 2024-12-11 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_designation_branch'),
        ('lead_management', '0002_alter_leadmodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSourceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_models', to='accounts.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_models', to='accounts.company')),
            ],
            options={
                'db_table': 'lead_source_table',
            },
        ),
    ]
