# Generated by Django 5.0.6 on 2024-12-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0003_leadsourcemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsourcemodel',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
