# Generated by Django 4.2.13 on 2024-07-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_company_address_company_company_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='annual_price',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='max_employees',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='package',
            name='monthly_price',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=20),
        ),
    ]
