# Generated by Django 4.2.13 on 2024-07-16 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_package_annual_price_package_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
    ]
