# Generated by Django 4.2.13 on 2024-08-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_formenquiry_rename_user_notice_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': (('can_view_own_company', 'Can view own company'), ('can_edit_own_company', 'Can edit own company'), ('can_delete_own_company', 'Can delete own company'), ('can_manage_own_company', 'Can manage own company')), 'verbose_name_plural': 'companies'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('month', 'Monthly'), ('quarter', 'Quarterly'), ('annual', 'Annually')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Pending'), (2, 'Resolved'), (3, 'Closed')], default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='modules',
            field=models.ManyToManyField(related_name='packages', to='accounts.module'),
        ),
    ]
