# Generated by Django 4.2.13 on 2024-09-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_module_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (2, 'Suspended'), (3, 'Deleted')], default=1),
        ),
    ]
