# Generated by Django 5.0.6 on 2024-09-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_company_bank_account_no_company_bank_account_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formenquiry',
            options={'verbose_name_plural': 'Form Enquiries'},
        ),
    ]
