# Generated by Django 4.2.13 on 2024-09-07 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_holiday_branch_userprofile_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appreciation',
            name='award_image',
            field=models.ImageField(blank=True, null=True, upload_to='award_images/'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shift_wise_attendances', to='accounts.shift'),
        ),
    ]
