# Generated by Django 5.0.6 on 2024-09-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_attendance_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance',
            field=models.CharField(choices=[('A', 'A'), ('P', 'P')], default='A', max_length=80),
        ),
    ]
