# Generated by Django 4.2.13 on 2024-09-09 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_leave_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': (('can_view_own_company', 'Can view own company'), ('can_edit_own_company', 'Can edit own company'), ('can_delete_own_company', 'Can delete own company'), ('can_manage_own_company', 'Can manage own company'), ('can_change_company_status', 'Can change company status')), 'verbose_name_plural': 'companies'},
        ),
        migrations.CreateModel(
            name='AllowedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_ip', to='accounts.branch')),
            ],
        ),
    ]
