# Generated by Django 5.0.6 on 2024-09-11 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_leave_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_shift_remark', models.TextField(blank=True, null=True)),
                ('tuesday_shift_remark', models.TextField(blank=True, null=True)),
                ('wednesday_shift_remark', models.TextField(blank=True, null=True)),
                ('thursday_shift_remark', models.TextField(blank=True, null=True)),
                ('friday_shift_remark', models.TextField(blank=True, null=True)),
                ('saturday_shift_remark', models.TextField(blank=True, null=True)),
                ('sunday_shift_remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_rosters', to='accounts.branch')),
                ('friday_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='friday_shift_rosters', to='accounts.shift')),
                ('monday_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monday_shift_rosters', to='accounts.shift')),
                ('saturday_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saturday_shift_rosters', to='accounts.shift')),
                ('sunday_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sunday_shift_rosters', to='accounts.shift')),
                ('thursday_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thursday_shift_rosters', to='accounts.shift')),
                ('tuesday_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tuesday_shift_rosters', to='accounts.shift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_rosters', to=settings.AUTH_USER_MODEL)),
                ('wednesday_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wednesday_shift_rosters', to='accounts.shift')),
            ],
            options={
                'db_table': 'shift_roster_table',
            },
        ),
    ]
