# Generated by Django 5.0.6 on 2024-09-13 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_attendance_clock_out'),
        ('superadmin_assets', '0002_rename_ulr_menumodel_url_submenumodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu', to='superadmin_assets.menumodel')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packagedetails', to='accounts.package')),
                ('submenu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submunuid', to='superadmin_assets.submenumodel')),
            ],
            options={
                'db_table': 'package_detail_table',
            },
        ),
    ]
