# Generated by Django 5.0.6 on 2024-09-13 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_packagedetailsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='modules',
        ),
    ]
