# Generated by Django 5.0.6 on 2024-10-07 08:40

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_customauthgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickUpPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person_name', models.CharField(max_length=255)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('contact_email', models.EmailField(max_length=100, unique=True)),
                ('alternate_contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('complete_address', models.CharField(max_length=255)),
                ('landmark', models.CharField(max_length=255)),
                ('pincode', models.IntegerField(max_length=6)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(related_name='pickup_branches', to='accounts.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_company', to='accounts.company')),
            ],
            options={
                'db_table': 'pick_up_point_table',
            },
        ),
    ]
