# Generated by Django 5.0.6 on 2024-10-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_userprofile_manager_userprofile_teamlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('agent', 'Agent')], default='agent', max_length=50),
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
