# Generated by Django 5.0.6 on 2024-11-19 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_userprofile_user_type_delete_userrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTargetsDelails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Target Amount')),
                ('interm_product', models.CharField(max_length=255, verbose_name='Interm Product')),
                ('interm_amount', models.CharField(max_length=255, verbose_name='Interm Amount')),
                ('daily_target', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Daily Target')),
                ('weekly_target', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Weekly Target')),
                ('achieve_target', models.BooleanField(default=False, verbose_name='Achieve Target')),
                ('in_use', models.BooleanField(default=True, verbose_name='In Use')),
                ('month', models.CharField(choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Target_branch', to='accounts.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Target_Company', to='accounts.company')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Target Table',
                'verbose_name_plural': 'Target Tables',
                'db_table': 'user_targets_details_table',
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='usertargetsdelails',
            constraint=models.CheckConstraint(check=models.Q(('target_amount__gte', 0)), name='check_target_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='usertargetsdelails',
            constraint=models.CheckConstraint(check=models.Q(('daily_target__gte', 0)), name='check_daily_target_positive'),
        ),
        migrations.AddConstraint(
            model_name='usertargetsdelails',
            constraint=models.CheckConstraint(check=models.Q(('weekly_target__gte', 0)), name='check_weekly_target_positive'),
        ),
    ]
