# Generated by Django 5.0.6 on 2024-11-20 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_usertargetsdelails_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255)),
                ('re_account_number', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('saving_account', 'Saving Account'), ('current_account', 'Current Account'), ('salary_account', 'Salary Account')], max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ifsc_code', models.CharField(max_length=255)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('branch_name', models.CharField(max_length=255)),
                ('priority', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_bank_details_branch', to='accounts.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_bank_details_company', to='accounts.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_bank_details_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_bank_details_table',
                'unique_together': {('user', 'priority')},
            },
        ),
    ]
