# Generated by Django 5.0.6 on 2024-11-22 06:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_adminbankdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedip',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ip_address_company', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='allowedip',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='allowedip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='allowedip',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_address_branch', to='accounts.branch'),
        ),
    ]
