# Generated by Django 5.0.6 on 2024-12-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_up', '0003_notepad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='follow_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pesponded', 'Responded'), ('deleted', 'Deleted')], max_length=255),
        ),
        migrations.AlterField(
            model_name='followup',
            name='snooze',
            field=models.CharField(choices=[('pending', 'Pending'), ('snooze', 'Snooze')], max_length=255),
        ),
    ]
