# Generated by Django 5.0.6 on 2024-12-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_up', '0004_alter_followup_follow_status_alter_followup_snooze'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followup',
            old_name='follow_addedBy',
            new_name='follow_add_by',
        ),
    ]
