# Generated by Django 5.0.6 on 2024-12-03 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_qctable'),
        ('follow_up', '0005_rename_follow_addedby_followup_follow_add_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup_branch', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='followup',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup_company', to='accounts.company'),
        ),
    ]
