# Generated by Django 5.0.6 on 2024-08-13 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_remove_userrole_company_userprofile_company_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudTelephonyChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.TextField()),
                ('api_json', models.TextField()),
                ('creadentials_json', models.TextField()),
                ('auth_tokent_ype', models.IntegerField(choices=[(0, 'No Auth'), (1, 'Bearer Token'), (2, 'JWT Bearer'), (3, 'Basic Auth')])),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'db_table': 'cloud_telephony_channel_table',
            },
        ),
    ]
