# Generated by Django 5.0.6 on 2024-08-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_telephony', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudtelephonychannel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='cloudtelephoney_channel_images/'),
        ),
    ]
