# Generated by Django 5.0.6 on 2024-08-13 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_telephony', '0002_alter_cloudtelephonychannel_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudtelephonychannel',
            name='api_json',
        ),
    ]
