# Generated by Django 5.0.6 on 2024-08-14 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_userrole_company_userprofile_company_branch_and_more'),
        ('cloud_telephony', '0004_cloudtelephonychannel_cloud_celephony_provider_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudTelephonyChannelAssign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cloud_telephony_channel_table', models.CharField(max_length=255)),
                ('cloud_celephony_provider_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telephony_channals_assign_table',
            },
        ),
    ]
