# Generated by Django 5.0.6 on 2024-08-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_telephony', '0005_cloudtelephonychannelassign'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudtelephonychannelassign',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
