# Generated by Django 5.0.6 on 2024-08-14 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_telephony', '0006_cloudtelephonychannelassign_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudtelephonychannelassign',
            name='cloud_telephony_channel_table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cloud_telephony.cloudtelephonychannel'),
        ),
    ]
