# Generated by Django 5.0.6 on 2024-11-22 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_qctable'),
        ('cloud_telephony', '0007_alter_cloudtelephonychannelassign_cloud_telephony_channel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMailSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=25)),
                ('hostname', models.CharField(max_length=255)),
                ('mail_smtp', models.CharField(max_length=255)),
                ('mail_port', models.IntegerField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'db_table': 'user_mail_setup_table',
            },
        ),
    ]
