# Generated by Django 5.0.6 on 2024-08-24 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_alter_company_company_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'state_table',
            },
        ),
        migrations.CreateModel(
            name='Payment_Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_status_table',
            },
        ),
        migrations.CreateModel(
            name='Payment_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_types_table',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'order_status_table',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'category_table',
            },
        ),
        migrations.CreateModel(
            name='Order_Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('network_ip', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_parent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_phone', models.CharField(max_length=50)),
                ('customer_alter_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('customer_address', models.TextField()),
                ('customer_postal', models.CharField(max_length=20)),
                ('customer_city', models.CharField(max_length=255)),
                ('customer_country', models.CharField(max_length=150)),
                ('product_details', models.TextField()),
                ('total_amount', models.FloatField()),
                ('gross_amount', models.FloatField()),
                ('discount', models.FloatField()),
                ('prepaid_amount', models.IntegerField()),
                ('order_ship_by', models.IntegerField(blank=True, null=True)),
                ('order_wayBill', models.CharField(blank=True, max_length=255, null=True)),
                ('order_remark', models.TextField()),
                ('repeat_order', models.IntegerField(choices=[(0, 'New'), (1, 'Repeat')])),
                ('is_booked', models.IntegerField(choices=[(0, 'Not Booked'), (1, 'Booked')])),
                ('service_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('call_id', models.CharField(blank=True, max_length=50, null=True)),
                ('course_order', models.IntegerField(default=0)),
                ('course_order_repeated', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('customer_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.customer_state')),
                ('order_created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.payment_status')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.payment_type')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.status')),
            ],
            options={
                'db_table': 'orders_table',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('product_sku', models.CharField(max_length=255)),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.CharField(max_length=100)),
                ('product_hsn_number', models.CharField(max_length=200)),
                ('product_gst_percent', models.IntegerField(choices=[(0, '0%'), (5, '5%'), (12, '12%'), (18, '18%'), (28, '28%')])),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product_description', models.TextField()),
                ('product_availability', models.IntegerField(choices=[(0, 'InStock'), (1, 'OutOfStock')])),
                ('product_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'Suspended'), (3, 'Deleted')])),
                ('product_created', models.DateTimeField(auto_now_add=True)),
                ('product_updated', models.DateTimeField(auto_now=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.categorymodel')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'products_table',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(default='0', max_length=200)),
                ('product_name', models.CharField(default='0', max_length=255)),
                ('product_qty', models.IntegerField()),
                ('product_price', models.FloatField()),
                ('product_total', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order_table')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.status')),
            ],
            options={
                'db_table': 'orders_details_table',
            },
        ),
    ]
