# Generated by Django 5.0.6 on 2024-08-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_table',
            name='product_details',
            field=models.JSONField(),
        ),
    ]
