# Generated by Django 5.0.6 on 2024-07-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_table',
            name='product_id',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='order_table',
            name='product_name',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='order_table',
            name='product_price',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='order_table',
            name='product_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_table',
            name='product_total',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product_id',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product_name',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
