# Generated by Django 5.0.6 on 2024-08-28 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderdetail_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product_total',
            new_name='product_total_price',
        ),
    ]
