# Generated by Django 5.0.6 on 2024-08-26 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_table_product_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLogModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('remark', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('astion_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order_table')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.status')),
            ],
            options={
                'db_table': 'order_log_table',
            },
        ),
    ]
