# Generated by Django 5.0.6 on 2024-07-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_table_product_id_order_table_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='orderID',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='orderStatus',
            new_name='order_status',
        ),
        migrations.RemoveField(
            model_name='order_table',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='order_table',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='order_table',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='order_table',
            name='product_qty',
        ),
        migrations.RemoveField(
            model_name='order_table',
            name='product_total',
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product_id',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product_name',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
