# Generated by Django 5.0.6 on 2024-09-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_product_total_orderdetail_product_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='gst_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product_mrp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='taxeble_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product_total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
