# Generated by Django 5.0.6 on 2024-08-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderlogmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlogmodel',
            old_name='astion_by',
            new_name='action_by',
        ),
    ]
