# Generated by Django 5.0.6 on 2024-09-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderdetail_gst_amount_orderdetail_product_mrp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_table',
            name='product_qty',
            field=models.IntegerField(default=0),
        ),
    ]
