# Generated by Django 5.0.6 on 2024-09-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_table_product_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_table',
            name='shipping_charges',
            field=models.IntegerField(default=0),
        ),
    ]
