# Generated by Django 5.0.6 on 2024-10-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_table_shipping_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_table',
            name='edd_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order_table',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order_table',
            name='zone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
