# Generated by Django 5.0.6 on 2024-10-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_table_edd_time_order_table_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_table',
            name='is_scheduled',
            field=models.IntegerField(choices=[(0, 'Not Schedule'), (1, 'Scheduled')], default=0),
        ),
    ]
