# Generated by Django 5.0.6 on 2024-11-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_table_is_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='description',
            field=models.TextField(default='Order Status'),
        ),
    ]
