# Generated by Django 5.0.6 on 2024-11-28 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_qctable'),
        ('orders', '0009_orderstatus_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_table',
            name='pick_up_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.pickuppoint'),
        ),
    ]
