# Generated by Django 5.0.6 on 2024-08-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rename_product_id_orderdetail_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product_id',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
