# Generated by Django 5.0.6 on 2024-08-26 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_orderdetail_product_orderdetail_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product_id',
            new_name='product',
        ),
    ]
