# Generated by Django 5.0.6 on 2024-08-26 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_rename_product_id_orderdetail_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product',
            new_name='product_id',
        ),
    ]
