# Generated by Django 5.0.6 on 2024-08-22 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_company_company_address_and_more'),
        ('orders', '0012_alter_categorymodel_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('product_sku', models.CharField(max_length=255)),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.CharField(max_length=100)),
                ('product_hsn_number', models.CharField(max_length=200)),
                ('product_gst_percent', models.IntegerField(choices=[(0, '0%'), (5, '5%'), (12, '12%'), (18, '18%'), (28, '28%')])),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product_description', models.TextField()),
                ('product_availability', models.IntegerField(choices=[(0, 'InStock'), (1, 'OutOfStock')])),
                ('product_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'Suspended'), (3, 'Deleted')])),
                ('product_created', models.DateTimeField(auto_now_add=True)),
                ('product_updated', models.DateTimeField(auto_now=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.categorymodel')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'products_table',
            },
        ),
    ]
