# Generated by Django 5.0.6 on 2024-08-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_rename_product_orderdetail_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product_id',
            new_name='product_id_id',
        ),
    ]
