# Generated by Django 5.0.6 on 2024-08-26 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_rename_product_id_id_orderdetail_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.productmodel', to_field='product_id'),
        ),
    ]
