# Generated by Django 5.0.6 on 2024-08-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_orderdetail_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='product_id',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
