# Generated by Django 5.0.6 on 2024-08-26 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_formenquiry_rename_user_notice_created_by_and_more'),
        ('orders', '0018_alter_orderdetail_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_type',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='payment_type',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
    ]
