# Generated by Django 5.0.6 on 2024-08-26 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_orderstatus_alter_order_table_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'order_status_table',
            },
        ),
        migrations.AlterField(
            model_name='order_table',
            name='order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.status'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.status'),
        ),
        migrations.AlterField(
            model_name='orderlogmodel',
            name='order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.status'),
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
