# Generated by Django 5.0.6 on 2024-08-26 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_orderstatus_alter_order_table_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='company_id',
        ),
    ]
