# Generated by Django 5.0.6 on 2024-08-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_rename_product_id_orderdetail_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
    ]
